[project]
name = "novelgenerator"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "alembic",
    "annotated-types",
    "anthropic",
    "anyio",
    "bcrypt",
    "cachetools",
    "certifi",
    "cffi",
    "charset-normalizer",
    "click",
    "colorama",
    "cryptography",
    "distro",
    "dnspython",
    "docstring-parser",
    "ecdsa",
    "email-validator",
    "fastapi",
    "google-auth",
    "google-genai",
    "greenlet",
    "h11",
    "httpcore",
    "httpx",
    "idna",
    "iniconfig",
    "jiter",
    "mako",
    "markupsafe",
    "mistune",
    "openai",
    "packaging",
    "partial-json-parser",
    "passlib",
    "pillow",
    "pillow-avif-plugin",
    "pluggy",
    "psycopg2-binary",
    "pyasn1",
    "pyasn1-modules",
    "pycparser",
    "pydantic",
    "pydantic-core",
    "pygments",
    "pytest",
    "python-dotenv",
    "python-jose",
    "python-multipart",
    "requests",
    "rsa",
    "six",
    "sniffio",
    "sqlalchemy",
    "sqlalchemy-utils",
    "starlette",
    "tenacity",
    "tqdm",
    "typing-extensions",
    "typing-inspection",
    "urllib3",
    "uvicorn",
    "websockets",
]
