from __future__ import annotations

from typing import Any
from uuid import UUID

from ....models.db_models import Asset
from ..contracts import PersistedToolMeta, ToolBinding, ToolBindingMeta, ToolExecutionOutcome, ToolSpec
from ..result_utils import invalid_result, make_result, valid_result
from .shared import filter_allowed_specs, is_non_journey, obj_schema


READ_IMAGE_TOOL = "read_image"


def _styled_prompt_text(value: Any) -> str:
    if not isinstance(value, dict):
        return ""
    parts = [str(value.get(key) or "").strip() for key in ("prefix", "content", "postfix")]
    return " ".join(part for part in parts if part).strip()


def _resolve_image_asset(db: Any, project_id: UUID, raw_image_id: Any) -> Asset | None:
    image_id = str(raw_image_id or "").strip()
    if not image_id:
        return None
    try:
        asset_id = UUID(image_id)
    except (ValueError, TypeError):
        return None
    return db.query(Asset).filter(Asset.id == asset_id, Asset.project_id == project_id).first()


def _build_metadata_message(asset: Asset, *, can_view: bool) -> str:
    lines: list[str] = [f"Image {asset.id}"]
    name = str(asset.name or "").strip()
    if name:
        lines.append(f"name: {name}")
    asset_type = str(asset.asset_type or "").strip()
    if asset_type:
        lines.append(f"type: {asset_type}")
    if asset.width and asset.height:
        lines.append(f"dimensions: {int(asset.width)}x{int(asset.height)}")

    prompt = _styled_prompt_text(asset.generation_prompt)
    if prompt:
        lines.append(f"generation prompt: {prompt}")
    positive = _styled_prompt_text(asset.generation_positive_prompt)
    if positive:
        lines.append(f"positive prompt: {positive}")
    negative = _styled_prompt_text(asset.generation_negative_prompt)
    if negative:
        lines.append(f"negative prompt: {negative}")

    provider = str(asset.generation_provider or "").strip()
    model = str(asset.generation_model or "").strip()
    if provider or model:
        lines.append(f"generated by: {'/'.join(part for part in (provider, model) if part)}")

    if not prompt and not positive and not negative:
        lines.append("(no generation prompt; likely a directly uploaded image)")

    lines.append(
        "The image itself is attached for you to view."
        if can_view
        else "The selected model does not support image input, so only metadata is provided."
    )
    return "\n".join(lines)


def _read_image_specs(ctx) -> list[ToolSpec]:
    if not is_non_journey(ctx):
        return []
    return filter_allowed_specs(
        ctx,
        [
            ToolSpec(
                name=READ_IMAGE_TOOL,
                description=(
                    "Read an image by its id (the UUID shown as the image's markdown alt text). "
                    "Returns the image's generation prompt and metadata, and shows you the image "
                    "itself when the active model supports image input."
                ),
                parameters=obj_schema(
                    {"image_id": {"type": "string", "description": "Target image (asset) UUID."}},
                    ["image_id"],
                ),
                auto_approve_category="read",
            ),
        ],
    )


def build_read_image_bindings(ctx) -> list[ToolBinding]:
    specs = _read_image_specs(ctx)
    if not specs:
        return []

    async def _validate(args, validation_ctx):
        asset = _resolve_image_asset(validation_ctx.db, validation_ctx.project_id, args.get("image_id"))
        if asset is None:
            return invalid_result("validate_read_image", "image_id must reference an existing image asset")
        return valid_result()

    async def _execute(args, execution_ctx):
        asset = _resolve_image_asset(execution_ctx.db, execution_ctx.project_id, args.get("image_id"))
        if asset is None:
            raise ValueError("Image asset not found for read_image")
        can_view = str(asset.mime_type or "").strip().startswith("image/")
        data: dict[str, Any] = {}
        if can_view:
            # image delivery is gated later, when the conversation is assembled
            data["image_asset_ids"] = [str(asset.id)]
        return ToolExecutionOutcome(
            lifecycle="applied",
            result=make_result(
                _build_metadata_message(asset, can_view=can_view),
                object_id=str(asset.id),
                data=data or None,
            ),
        )

    return [
        ToolBinding(
            spec=specs[0],
            meta=ToolBindingMeta(
                feature_key="image",
                category="read",
                op="read",
                target_kind="object_image",
            ),
            validate=_validate,
            execute=_execute,
            build_persisted_meta=lambda _ctx, _args: PersistedToolMeta(
                feature_key="image",
                category="read",
                op="read",
                target_kind="object_image",
                target_id=None,
                merge_key=None,
            ),
        )
    ]
