from __future__ import annotations

from ..shared.contracts import (
    Condition,
    FieldSpec,
    ImageModelDescriptor,
    ImageModelGeometrySpec,
    ImageSpec,
    ObjectSpec,
    ProviderSpec,
    ProviderUI,
    RuntimeSpec,
    UIHint,
)


SPEC = ProviderSpec(
    id="novelai",
    ui=ProviderUI(
        display_name_key="settings.credentials.novelai.title",
        icon_key="novelai",
        image_order=40,
    ),
    credentials=ObjectSpec(fields={
        "api_key": FieldSpec(
            kind="string",
            required=True,
            ui=UIHint(
                widget="password",
                label_key="settings.credentials.accessToken",
                placeholder_key="settings.credentials.novelai.placeholder",
                help_key="settings.credentials.novelai.hint",
            ),
        ),
    }),
    image=ImageSpec(
        runtime=RuntimeSpec(adapter="default"),
        prompt_type="tag_based",
        supports_image_input=True,
        catalog_cache_policy="static",
        settings_title_key="settings.imageGen.novelaiSettings.title",
        settings_description_key="settings.imageGen.novelaiSettings.description",
        provider_settings=ObjectSpec(fields={
            "sampler": FieldSpec(
                kind="enum",
                default="k_euler_ancestral",
                options=("k_euler_ancestral", "k_euler", "k_dpmpp_2s_ancestral", "k_dpmpp_2m", "k_dpmpp_sde", "ddim_v3"),
                ui=UIHint(
                    widget="select",
                    label_key="settings.imageGen.novelaiSettings.sampler",
                    help_key="settings.imageGen.novelaiSettings.samplerHint",
                    order=10,
                ),
            ),
            "steps": FieldSpec(
                kind="int",
                default=28,
                min_value=1,
                max_value=50,
                ui=UIHint(
                    widget="number",
                    label_key="settings.imageGen.novelaiSettings.steps",
                    help_key="settings.imageGen.novelaiSettings.stepsHint",
                    order=20,
                ),
            ),
            "scale": FieldSpec(
                kind="number",
                default=6.0,
                min_value=1,
                max_value=20,
                step=0.5,
                ui=UIHint(
                    widget="number",
                    label_key="settings.imageGen.novelaiSettings.cfgScale",
                    help_key="settings.imageGen.novelaiSettings.cfgScaleHint",
                    order=30,
                ),
            ),
            "noise_schedule": FieldSpec(
                kind="enum",
                default="karras",
                options=("native", "karras", "exponential", "polyexponential"),
                ui=UIHint(
                    widget="select",
                    label_key="settings.imageGen.novelaiSettings.noiseSchedule",
                    help_key="settings.imageGen.novelaiSettings.noiseScheduleHint",
                    order=40,
                ),
            ),
            "referenceMode": FieldSpec(
                kind="enum",
                default="auto",
                options=("auto", "i2i", "vibe"),
                when=(Condition(op="flag", flag="hasReferenceImages"),),
                ui=UIHint(
                    widget="select",
                    label_key="settings.imageGen.novelaiSettings.referenceMode",
                    help_key="settings.imageGen.novelaiSettings.referenceModeHint",
                    option_label_prefix="settings.imageGen.novelaiSettings.referenceModeOptions",
                    section="reference",
                    order=50,
                ),
            ),
            "strength": FieldSpec(
                kind="number",
                default=0.7,
                min_value=0,
                max_value=1,
                step=0.05,
                when=(Condition(op="flag", flag="hasReferenceImages"), Condition(op="neq", path="referenceMode", value="vibe")),
                ui=UIHint(
                    widget="slider",
                    label_key="settings.imageGen.novelaiSettings.strength",
                    help_key="settings.imageGen.novelaiSettings.strengthHint",
                    section="reference",
                    order=60,
                ),
            ),
            "i2iNoise": FieldSpec(
                kind="number",
                default=0.0,
                min_value=0,
                max_value=1,
                step=0.05,
                when=(Condition(op="flag", flag="hasReferenceImages"), Condition(op="neq", path="referenceMode", value="vibe")),
                ui=UIHint(
                    widget="slider",
                    label_key="settings.imageGen.novelaiSettings.i2iNoise",
                    help_key="settings.imageGen.novelaiSettings.i2iNoiseHint",
                    section="reference",
                    order=70,
                ),
            ),
            "vibeStrength": FieldSpec(
                kind="number",
                default=0.6,
                min_value=0,
                max_value=1,
                step=0.05,
                when=(Condition(op="flag", flag="hasReferenceImages"), Condition(op="neq", path="referenceMode", value="i2i")),
                ui=UIHint(
                    widget="slider",
                    label_key="settings.imageGen.novelaiSettings.vibeStrength",
                    help_key="settings.imageGen.novelaiSettings.vibeStrengthHint",
                    section="reference",
                    order=80,
                ),
            ),
            "vibeInfoExtracted": FieldSpec(
                kind="number",
                default=1.0,
                min_value=0,
                max_value=1,
                step=0.05,
                when=(Condition(op="flag", flag="hasReferenceImages"), Condition(op="neq", path="referenceMode", value="i2i")),
                ui=UIHint(
                    widget="slider",
                    label_key="settings.imageGen.novelaiSettings.vibeInfoExtracted",
                    help_key="settings.imageGen.novelaiSettings.vibeInfoExtractedHint",
                    section="reference",
                    order=90,
                ),
            ),
        }),
        models=(
            ImageModelDescriptor(
                id="nai-diffusion-4-5-full",
                name="NAI Diffusion V4.5 Full",
                prompt_type="tag_based",
                supports_image_input=True,
                geometry=ImageModelGeometrySpec(
                    supported_aspect_ratios=("1:1", "13:19", "19:13", "2:3", "3:2", "5:12", "12:5"),
                    supported_resolutions=("1K",),
                    default_aspect_ratio="13:19",
                    default_resolution="1K",
                    resolution_mode="translated_fixed",
                    native_size_by_ratio={
                        "1:1": "1024x1024",
                        "13:19": "832x1216",
                        "19:13": "1216x832",
                        "2:3": "1024x1536",
                        "3:2": "1536x1024",
                        "5:12": "640x1536",
                        "12:5": "1536x640",
                    },
                ),
            ),
            ImageModelDescriptor(
                id="nai-diffusion-4-5-curated",
                name="NAI Diffusion V4.5 Curated",
                prompt_type="tag_based",
                supports_image_input=True,
                geometry=ImageModelGeometrySpec(
                    supported_aspect_ratios=("1:1", "13:19", "19:13", "2:3", "3:2", "5:12", "12:5"),
                    supported_resolutions=("1K",),
                    default_aspect_ratio="13:19",
                    default_resolution="1K",
                    resolution_mode="translated_fixed",
                    native_size_by_ratio={
                        "1:1": "1024x1024",
                        "13:19": "832x1216",
                        "19:13": "1216x832",
                        "2:3": "1024x1536",
                        "3:2": "1536x1024",
                        "5:12": "640x1536",
                        "12:5": "1536x640",
                    },
                ),
            ),
        ),
    ),
)
